import { getDb, isDevDb } from "./db";

export type Role = "admin" | "viterbo" | "gran_sasso";
export type Store = "Viterbo" | "Gran Sasso";

export type SessionUser = {
  id: number;
  username: string;
  displayName: string;
  role: Role;
  store: Store | null;
  mustChangePassword: number;
};

type D1RunResult = { success?: boolean; meta?: { last_row_id?: number; changes?: number } };
type D1AllResult<T> = { results?: T[] };

export type D1Statement = {
  bind: (...values: unknown[]) => D1Statement;
  first: <T = Record<string, unknown>>(columnName?: string) => Promise<T | null>;
  all: <T = Record<string, unknown>>() => Promise<D1AllResult<T>>;
  run: () => Promise<D1RunResult>;
};

export type D1Database = {
  prepare: (sql: string) => D1Statement;
  batch: (statements: D1Statement[]) => Promise<D1RunResult[]>;
};

export function database(): D1Database {
  return getDb() as unknown as D1Database;
}

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, role TEXT NOT NULL, store TEXT, password_salt TEXT NOT NULL, password_hash TEXT NOT NULL, password_iterations INTEGER NOT NULL DEFAULT 100000, must_change_password INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS customers (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_type TEXT NOT NULL DEFAULT 'private', first_name TEXT NOT NULL, last_name TEXT NOT NULL, company_name TEXT, vat_number TEXT, pec TEXT, sdi_code TEXT, phone TEXT, email TEXT, address TEXT, postal_code TEXT, city TEXT, province TEXT, tax_code TEXT, scope TEXT NOT NULL, created_store TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS catalog_products (id TEXT PRIMARY KEY, name TEXT NOT NULL, brand TEXT NOT NULL DEFAULT '', category TEXT, base_price double precision NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS products (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sku TEXT NOT NULL UNIQUE, name TEXT NOT NULL, brand TEXT NOT NULL DEFAULT '', category TEXT, color TEXT, size TEXT, price double precision NOT NULL, variant_group TEXT, photo_key TEXT, active INTEGER NOT NULL DEFAULT 1)`,
  `CREATE TABLE IF NOT EXISTS product_eans (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE, ean TEXT NOT NULL UNIQUE)`,
  `CREATE TABLE IF NOT EXISTS inventory (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE, store TEXT NOT NULL, quantity INTEGER NOT NULL DEFAULT 0, reserved INTEGER NOT NULL DEFAULT 0, reorder_level INTEGER NOT NULL DEFAULT 2, UNIQUE(product_id, store))`,
  `CREATE TABLE IF NOT EXISTS sales (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, receipt_no TEXT NOT NULL UNIQUE, store TEXT NOT NULL, customer_id INTEGER REFERENCES customers(id), type TEXT NOT NULL, subtotal double precision NOT NULL, adjustment double precision NOT NULL DEFAULT 0, total double precision NOT NULL, cash_amount double precision NOT NULL DEFAULT 0, card_amount double precision NOT NULL DEFAULT 0, bank_amount double precision NOT NULL DEFAULT 0, gift_amount double precision NOT NULL DEFAULT 0, gift_code_used TEXT, fiscal_status TEXT NOT NULL DEFAULT 'pending', fiscal_document_type TEXT NOT NULL DEFAULT 'receipt', created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sale_items (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE, product_id INTEGER REFERENCES products(id), description TEXT NOT NULL, quantity double precision NOT NULL, unit_price double precision NOT NULL, line_total double precision NOT NULL, discount_percent double precision NOT NULL DEFAULT 0, item_type TEXT NOT NULL, metadata TEXT)`,
  `CREATE TABLE IF NOT EXISTS fiscal_devices (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, store TEXT NOT NULL UNIQUE, vendor TEXT NOT NULL, model TEXT NOT NULL, connector TEXT NOT NULL, token_hash TEXT, enabled INTEGER NOT NULL DEFAULT 0, last_seen_at TEXT, last_status TEXT NOT NULL DEFAULT 'not_configured', last_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS fiscal_jobs (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sale_id INTEGER NOT NULL UNIQUE REFERENCES sales(id) ON DELETE CASCADE, store TEXT NOT NULL, job_type TEXT NOT NULL, payload TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', attempts INTEGER NOT NULL DEFAULT 0, device_response TEXT, created_at TEXT NOT NULL, claimed_at TEXT, completed_at TEXT, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS gift_cards (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code TEXT NOT NULL UNIQUE, beneficiary TEXT NOT NULL, initial_value double precision NOT NULL, balance double precision NOT NULL, expires_at TEXT NOT NULL, store TEXT NOT NULL, issued_sale_id INTEGER NOT NULL REFERENCES sales(id), status TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS reservations (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code TEXT NOT NULL UNIQUE, store TEXT NOT NULL, customer_id INTEGER REFERENCES customers(id), product_id INTEGER REFERENCES products(id), description TEXT NOT NULL, kind TEXT NOT NULL, total_price double precision NOT NULL, deposit_amount double precision NOT NULL, balance_due double precision NOT NULL, status TEXT NOT NULL, issued_sale_id INTEGER NOT NULL REFERENCES sales(id), redeemed_sale_id INTEGER REFERENCES sales(id), created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS reservation_items (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, reservation_id INTEGER NOT NULL REFERENCES reservations(id) ON DELETE CASCADE, product_id INTEGER REFERENCES products(id), description TEXT NOT NULL, quantity INTEGER NOT NULL, unit_price double precision NOT NULL, discount_percent double precision NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS transfers (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code TEXT NOT NULL UNIQUE, from_store TEXT NOT NULL, to_store TEXT NOT NULL, sender TEXT NOT NULL DEFAULT '', receiver TEXT NOT NULL DEFAULT '', carrier TEXT NOT NULL DEFAULT '', transport_reason TEXT NOT NULL DEFAULT 'Trasferimento merce', status TEXT NOT NULL DEFAULT 'accepted', note TEXT, completed_at TEXT, created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS transfer_items (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transfer_id INTEGER NOT NULL REFERENCES transfers(id) ON DELETE CASCADE, product_id INTEGER REFERENCES products(id) ON DELETE SET NULL, description TEXT NOT NULL DEFAULT '', quantity INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS business_documents (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, number TEXT NOT NULL UNIQUE, type TEXT NOT NULL, customer_id INTEGER REFERENCES customers(id), recipient TEXT NOT NULL, recipient_vat_number TEXT, recipient_pec TEXT, recipient_sdi_code TEXT, recipient_address TEXT, recipient_postal_code TEXT, recipient_city TEXT, recipient_province TEXT, origin TEXT NOT NULL, payment_method TEXT NOT NULL DEFAULT 'cash', sale_id INTEGER REFERENCES sales(id), net_total double precision NOT NULL DEFAULT 0, tax_total double precision NOT NULL DEFAULT 0, total double precision NOT NULL, created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS business_document_items (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES business_documents(id) ON DELETE CASCADE, product_id INTEGER REFERENCES products(id), description TEXT NOT NULL, quantity double precision NOT NULL, unit_price double precision NOT NULL, line_total double precision NOT NULL, tax_rate double precision NOT NULL DEFAULT 22, tax_amount double precision NOT NULL DEFAULT 0, gross_total double precision NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS activity_log (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT NOT NULL, user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, username TEXT NOT NULL DEFAULT '', action TEXT NOT NULL, entity TEXT NOT NULL, entity_id INTEGER, detail TEXT NOT NULL DEFAULT '', store TEXT)`,
  `CREATE INDEX IF NOT EXISTS activity_log_created_idx ON activity_log(created_at)`,
  `CREATE INDEX IF NOT EXISTS activity_log_entity_idx ON activity_log(entity, entity_id)`,
  `CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at)`,
  `CREATE INDEX IF NOT EXISTS customers_name_idx ON customers(last_name, first_name)`,
  `CREATE INDEX IF NOT EXISTS sales_customer_idx ON sales(customer_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS sales_store_date_idx ON sales(store, created_at)`,
  `CREATE INDEX IF NOT EXISTS product_eans_product_idx ON product_eans(product_id)`,
  `CREATE INDEX IF NOT EXISTS reservation_items_reservation_idx ON reservation_items(reservation_id)`,
  `CREATE INDEX IF NOT EXISTS fiscal_jobs_store_status_idx ON fiscal_jobs(store, status, created_at)`,
];

function bytesToBase64(bytes: Uint8Array) {
  let value = "";
  for (const byte of bytes) value += String.fromCharCode(byte);
  return btoa(value);
}

function randomToken(byteLength = 24) {
  const bytes = new Uint8Array(byteLength);
  crypto.getRandomValues(bytes);
  return bytesToBase64(bytes).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
}

// Cloudflare Workers Web Crypto currently accepts at most 100,000 PBKDF2 iterations.
export const PASSWORD_HASH_ITERATIONS = 100_000;

export async function hashPassword(password: string, salt: string, iterations = PASSWORD_HASH_ITERATIONS) {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", hash: "SHA-256", salt: encoder.encode(salt), iterations },
    key,
    256,
  );
  return bytesToBase64(new Uint8Array(bits));
}

export function passwordStrengthError(password: string) {
  if (password.length < 12) return "Usa almeno 12 caratteri.";
  if (!/[a-z]/.test(password) || !/[A-Z]/.test(password) || !/\d/.test(password) || !/[^A-Za-z0-9]/.test(password)) {
    return "Usa almeno una lettera maiuscola, una minuscola, un numero e un simbolo.";
  }
  return null;
}

export async function createPasswordCredential(password: string) {
  const salt = randomToken(24);
  return {
    salt,
    hash: await hashPassword(password, salt, PASSWORD_HASH_ITERATIONS),
    iterations: PASSWORD_HASH_ITERATIONS,
  };
}

export async function hashToken(token: string) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(token));
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

async function seedProducts() {
  const db = database();
  const rows = [
    ["SCARP-TRK-BLU-42", "Scarpa Trekking Alta", "Calzature", "Blu", "42", 129.9, ["8051000000013", "8051000000112"]],
    ["SCARP-TRK-BLU-43", "Scarpa Trekking Alta", "Calzature", "Blu", "43", 129.9, ["8051000000020"]],
    ["SCARP-TRK-NER-42", "Scarpa Trekking Alta", "Calzature", "Nero", "42", 129.9, ["8051000000037"]],
    ["MAG-GS-BLU-M", "Maglia Gran Sasso", "Abbigliamento", "Blu", "M", 39.9, ["8051000000044"]],
    ["MAG-GS-VER-L", "Maglia Gran Sasso", "Abbigliamento", "Verde", "L", 39.9, ["8051000000051"]],
    ["ZAINO-TRAIL-30", "Zaino Trail 30L", "Attrezzatura", "Rosso", "Unica", 89, ["8051000000068", "8051000000167"]],
  ] as const;

  for (const row of rows) {
    await db.prepare(`INSERT OR IGNORE INTO products (sku, name, category, color, size, price, active) VALUES (?, ?, ?, ?, ?, ?, 1)`)
      .bind(row[0], row[1], row[2], row[3], row[4], row[5]).run();
    const product = await db.prepare(`SELECT id FROM products WHERE sku = ?`).bind(row[0]).first<{ id: number }>();
    if (!product) continue;
    for (const ean of row[6]) {
      await db.prepare(`INSERT OR IGNORE INTO product_eans (product_id, ean) VALUES (?, ?)`).bind(product.id, ean).run();
    }
    await db.prepare(`INSERT OR IGNORE INTO inventory (product_id, store, quantity, reserved) VALUES (?, 'Viterbo', 6, 0)`).bind(product.id).run();
    await db.prepare(`INSERT OR IGNORE INTO inventory (product_id, store, quantity, reserved) VALUES (?, 'Gran Sasso', 4, 0)`).bind(product.id).run();
  }
}

// Catalogo demo ricco, solo in sviluppo (pglite): serve a vedere magazzino,
// dashboard e "articoli da riordinare" pieni. Alcuni con giacenza bassa.
async function seedDemoProducts() {
  const db = database();
  let ean = 8052000000000;
  const nextEan = () => String(++ean);
  // [name, category, brand, price, [ [color,size,vtQty,gsQty], ... ] ]
  const catalog: [string, string, string, number, [string, string, number, number][]][] = [
    ["Scarpa Trekking Alta", "Calzature", "Salewa", 129.9, [["Blu", "42", 6, 4], ["Blu", "43", 1, 0], ["Nero", "42", 0, 2], ["Nero", "44", 3, 3]]],
    ["Scarpone Alpinismo", "Calzature", "La Sportiva", 249, [["Grigio", "43", 2, 1], ["Grigio", "44", 0, 0], ["Arancio", "42", 4, 2]]],
    ["Sandalo Trekking", "Calzature", "Teva", 69.9, [["Marrone", "41", 5, 5], ["Marrone", "43", 1, 2]]],
    ["Maglia Tecnica", "Abbigliamento", "Salewa", 39.9, [["Blu", "M", 8, 6], ["Verde", "L", 2, 1], ["Rosso", "S", 0, 4]]],
    ["Pile Micropile", "Abbigliamento", "CMP", 49.9, [["Antracite", "M", 3, 2], ["Antracite", "L", 1, 0], ["Blu", "XL", 6, 5]]],
    ["Giacca Antipioggia", "Abbigliamento", "The North Face", 159, [["Nero", "M", 2, 2], ["Nero", "L", 0, 1], ["Giallo", "M", 4, 0]]],
    ["Pantalone Trekking", "Abbigliamento", "Millet", 79.9, [["Beige", "48", 5, 3], ["Beige", "50", 1, 1], ["Nero", "52", 2, 0]]],
    ["Zaino Trail 30L", "Attrezzatura", "Deuter", 89, [["Rosso", "Unica", 4, 2], ["Blu", "Unica", 1, 0]]],
    ["Zaino Alpino 45L", "Attrezzatura", "Osprey", 149, [["Verde", "Unica", 2, 1], ["Grigio", "Unica", 0, 0]]],
    ["Bastoncini Trekking", "Attrezzatura", "Leki", 59.9, [["Nero", "Unica", 7, 4], ["Blu", "Unica", 2, 2]]],
    ["Borraccia Termica", "Accessori", "Salewa", 24.9, [["Acciaio", "0.75L", 10, 8], ["Nero", "1L", 1, 0]]],
    ["Calze Merino", "Accessori", "X-Socks", 18.9, [["Grigio", "39-41", 12, 9], ["Grigio", "42-44", 3, 1], ["Nero", "45-47", 0, 2]]],
    ["Berretto Lana", "Accessori", "CMP", 19.9, [["Rosso", "Unica", 6, 5], ["Blu", "Unica", 1, 0]]],
    ["Frontale LED", "Attrezzatura", "Petzl", 44.9, [["Nero", "Unica", 3, 2], ["Arancio", "Unica", 0, 1]]],
    ["Guanti Impermeabili", "Accessori", "Reusch", 34.9, [["Nero", "M", 4, 3], ["Nero", "L", 1, 1], ["Grigio", "XL", 0, 0]]],
  ];
  for (const [name, category, brand, price, variants] of catalog) {
    for (const [color, size, vt, gs] of variants) {
      const sku = `${name.split(" ").map((w) => w.slice(0, 3)).join("").toUpperCase()}-${color.slice(0, 3).toUpperCase()}-${size}`.replace(/[^A-Z0-9-]/g, "");
      await db.prepare(`INSERT OR IGNORE INTO products (sku, name, brand, category, color, size, price, active) VALUES (?, ?, ?, ?, ?, ?, ?, 1)`)
        .bind(sku, name, brand, category, color, size, price).run();
      const product = await db.prepare(`SELECT id FROM products WHERE sku = ?`).bind(sku).first<{ id: number }>();
      if (!product) continue;
      await db.prepare(`INSERT OR IGNORE INTO product_eans (product_id, ean) VALUES (?, ?)`).bind(product.id, nextEan()).run();
      await db.prepare(`INSERT OR IGNORE INTO inventory (product_id, store, quantity, reserved, reorder_level) VALUES (?, 'Viterbo', ?, 0, 2)`).bind(product.id, vt).run();
      await db.prepare(`INSERT OR IGNORE INTO inventory (product_id, store, quantity, reserved, reorder_level) VALUES (?, 'Gran Sasso', ?, 0, 2)`).bind(product.id, gs).run();
    }
  }
}

export async function ensureDatabase() {
  const db = database();
  await db.batch(schemaStatements.map((statement) => db.prepare(statement)));
  await db.batch([
    db.prepare(`DELETE FROM sessions WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE key = 'firebase_auth_cutover_v1')`),
    db.prepare(`INSERT OR IGNORE INTO app_settings (key, value) VALUES ('firebase_auth_cutover_v1', ?)` ).bind(new Date().toISOString()),
  ]);
  // Postgres: le colonne aggiunte in evoluzione si creano idempotenti.
  await db.prepare(`ALTER TABLE users ADD COLUMN IF NOT EXISTS password_iterations INTEGER NOT NULL DEFAULT 100000`).run();
  await db.prepare(`ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password INTEGER NOT NULL DEFAULT 1`).run();
  await db.prepare(`ALTER TABLE customers ADD COLUMN IF NOT EXISTS active INTEGER NOT NULL DEFAULT 1`).run();
  await db.prepare(`ALTER TABLE inventory ADD COLUMN IF NOT EXISTS reorder_level INTEGER NOT NULL DEFAULT 2`).run();
  await db.prepare(`ALTER TABLE transfer_items ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT ''`).run();
  await db.prepare(`ALTER TABLE transfers ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'accepted'`).run();
  await db.prepare(`ALTER TABLE transfers ADD COLUMN IF NOT EXISTS note TEXT`).run();
  await db.prepare(`ALTER TABLE transfers ADD COLUMN IF NOT EXISTS completed_at TEXT`).run();
  try { await db.prepare(`ALTER TABLE transfer_items ALTER COLUMN product_id DROP NOT NULL`).run(); } catch { /* già nullable */ }
  await db.prepare(`UPDATE users SET username = 'admin', display_name = 'Amministratore', role = 'admin', store = NULL, must_change_password = 0 WHERE username = 'amministratore' AND NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin')`).run();
  await db.prepare(`UPDATE users SET display_name = 'Cassa Viterbo', role = 'viterbo', store = 'Viterbo', must_change_password = 0 WHERE username = 'viterbo'`).run();
  await db.prepare(`UPDATE users SET display_name = 'Cassa Gran Sasso', role = 'gran_sasso', store = 'Gran Sasso', must_change_password = 0 WHERE username = 'gran-sasso'`).run();
  const seeded = await db.prepare(`SELECT value FROM app_settings WHERE key = 'initial_seed_completed'`).first<{ value: string }>();
  if (!seeded) {
    const products = await db.prepare(`SELECT COUNT(*) AS count FROM products`).first<{ count: number }>();
    if (!products?.count) await (isDevDb() ? seedDemoProducts() : seedProducts());
    await db.prepare(`INSERT OR REPLACE INTO app_settings (key, value) VALUES ('initial_seed_completed', '1')`).run();
  }
  await db.prepare(`UPDATE products SET variant_group = 'legacy-' || (
    SELECT MIN(p2.id) FROM products p2
    WHERE LOWER(COALESCE(p2.brand, '')) = LOWER(COALESCE(products.brand, ''))
      AND LOWER(p2.name) = LOWER(products.name)
      AND LOWER(COALESCE(p2.category, '')) = LOWER(COALESCE(products.category, ''))
  ) WHERE variant_group IS NULL OR variant_group = ''`).run();
  await db.prepare(`INSERT OR IGNORE INTO catalog_products (id, name, brand, category, base_price, active, created_at)
    SELECT variant_group, MIN(name), MIN(brand), MIN(category), MIN(price), MAX(active), ?
    FROM products WHERE variant_group IS NOT NULL AND variant_group <> '' GROUP BY variant_group`).bind(new Date().toISOString()).run();
  const now = new Date().toISOString();
  await db.prepare(`INSERT OR IGNORE INTO fiscal_devices (store, vendor, model, connector, enabled, last_status, created_at, updated_at) VALUES ('Viterbo', 'RCH', 'PRINT! 3.0 RT', 'rch_standard_tcp', 0, 'not_configured', ?, ?)`).bind(now, now).run();
  await db.prepare(`UPDATE fiscal_devices SET connector = 'rch_standard_tcp', updated_at = ? WHERE store = 'Viterbo' AND connector = 'rch_webservice'`).bind(now).run();
  await db.prepare(`INSERT OR IGNORE INTO fiscal_devices (store, vendor, model, connector, enabled, last_status, created_at, updated_at) VALUES ('Gran Sasso', 'Epson', 'FP-81 II RT', 'epson_fpmate', 0, 'not_configured', ?, ?)`).bind(now, now).run();
}

function cookieValue(request: Request, name: string) {
  const cookies = request.headers.get("cookie") ?? "";
  for (const cookie of cookies.split(";")) {
    const [key, ...value] = cookie.trim().split("=");
    if (key === name) return decodeURIComponent(value.join("="));
  }
  return null;
}

/** Vero se il client e' in modalita' TEST (cookie gestionale_mode=test). */
export function isTestMode(request: Request): boolean {
  return cookieValue(request, "gestionale_mode") === "test";
}

export async function currentUser(request: Request): Promise<SessionUser | null> {
  await ensureDatabase();
  const token = cookieValue(request, "gestionale_session");
  if (!token) return null;
  const tokenHash = await hashToken(token);
  const row = await database().prepare(`SELECT u.id, u.username, u.display_name AS displayName, u.role, u.store, u.must_change_password AS mustChangePassword FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.token IN (?, ?) AND s.expires_at > ?`)
    .bind(tokenHash, token, new Date().toISOString()).first<SessionUser>();
  if (row) await database().prepare(`UPDATE OR IGNORE sessions SET token = ? WHERE token = ?`).bind(tokenHash, token).run();
  return row ?? null;
}

export async function createSession(userId: number, maxAgeSeconds = 55 * 60) {
  const token = randomToken(32);
  const tokenHash = await hashToken(token);
  const now = new Date();
  const expires = new Date(now.getTime() + maxAgeSeconds * 1000);
  await database().prepare(`DELETE FROM sessions WHERE expires_at <= ?`).bind(now.toISOString()).run();
  await database().prepare(`INSERT INTO sessions (token, user_id, expires_at, created_at) VALUES (?, ?, ?, ?)`)
    .bind(tokenHash, userId, expires.toISOString(), now.toISOString()).run();
  return {
    token,
    cookie: `gestionale_session=${encodeURIComponent(token)}; Path=/; HttpOnly${cookieSecure()}; SameSite=Strict; Max-Age=${maxAgeSeconds}`,
  };
}

// `Secure` solo in produzione: su http://localhost i cookie Secure vengono
// scartati da alcuni browser, impedendo il login in sviluppo.
export function cookieSecure() {
  return process.env.DATABASE_URL ? "; Secure" : "";
}

export async function removeSession(request: Request) {
  const token = cookieValue(request, "gestionale_session");
  if (token) await database().prepare(`DELETE FROM sessions WHERE token IN (?, ?)`).bind(await hashToken(token), token).run();
}

export async function logActivity(entry: { user?: SessionUser | null; action: string; entity: string; entityId?: number | null; detail?: string; store?: string | null }) {
  try {
    await database().prepare(`INSERT INTO activity_log (created_at, user_id, username, action, entity, entity_id, detail, store) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`)
      .bind(new Date().toISOString(), entry.user?.id ?? null, entry.user?.username ?? "", entry.action, entry.entity, entry.entityId ?? null, entry.detail ?? "", entry.store ?? entry.user?.store ?? null).run();
  } catch { /* il log non deve mai bloccare l'operazione principale */ }
}

export function idCode(prefix: string) {
  const stamp = new Date().toISOString().replace(/\D/g, "").slice(2, 14);
  return `${prefix}-${stamp}-${Math.floor(100 + Math.random() * 900)}`;
}

export function ean13() {
  const base = `29${Date.now().toString().slice(-10)}`.slice(0, 12);
  let sum = 0;
  for (let index = 0; index < 12; index += 1) sum += Number(base[index]) * (index % 2 === 0 ? 1 : 3);
  return `${base}${(10 - (sum % 10)) % 10}`;
}

export function json(data: unknown, status = 200, headers?: HeadersInit) {
  return Response.json(data, { status, headers });
}
