-- Gestionale Marinelli — schema Postgres (Supabase)
-- Fonte di verità dello schema. Da eseguire sul progetto Supabase (SQL editor)
-- prima del primo avvio. L'app (ensureDatabase) crea comunque le tabelle
-- mancanti in modo idempotente, ma questo file è quello "fatto bene":
-- foreign key con ON DELETE corretti, vincoli CHECK, indici, tabella negozi.
--
-- Scelte:
--  * importi in double precision (compatibile con la matematica JS attuale).
--  * date come TEXT ISO 8601 (l'app le salva/legge così).
--  * eliminazione prodotto: EAN e giacenze spariscono (CASCADE); le righe
--    storiche (vendite, prenotazioni, documenti, DDT) mantengono la descrizione
--    e perdono solo il riferimento (SET NULL) → lo storico resta leggibile.

BEGIN;

-- Negozi (predisposizione multi-negozio). I riferimenti restano per nome.
CREATE TABLE IF NOT EXISTS stores (
  name TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT ''
);
INSERT INTO stores (name, code, created_at) VALUES
  ('Viterbo', 'viterbo', ''),
  ('Gran Sasso', 'gran-sasso', '')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin','viterbo','gran_sasso')),
  store TEXT REFERENCES stores(name),
  password_salt TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  password_iterations INTEGER NOT NULL DEFAULT 100000,
  must_change_password INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_type TEXT NOT NULL DEFAULT 'private' CHECK (customer_type IN ('private','company')),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  company_name TEXT,
  vat_number TEXT,
  pec TEXT,
  sdi_code TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  postal_code TEXT,
  city TEXT,
  province TEXT,
  tax_code TEXT,
  scope TEXT NOT NULL,
  created_store TEXT NOT NULL REFERENCES stores(name),
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS catalog_products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL DEFAULT '',
  category TEXT,
  base_price double precision NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  brand TEXT NOT NULL DEFAULT '',
  category TEXT,
  color TEXT,
  size TEXT,
  price double precision NOT NULL,
  variant_group TEXT REFERENCES catalog_products(id) ON DELETE SET NULL,
  photo_key TEXT,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS product_eans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  ean TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS inventory (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  store TEXT NOT NULL REFERENCES stores(name),
  quantity INTEGER NOT NULL DEFAULT 0,
  reserved INTEGER NOT NULL DEFAULT 0,
  reorder_level INTEGER NOT NULL DEFAULT 2,
  UNIQUE (product_id, store)
);

CREATE TABLE IF NOT EXISTS sales (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_no TEXT NOT NULL UNIQUE,
  store TEXT NOT NULL REFERENCES stores(name),
  customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL,
  type TEXT NOT NULL,
  subtotal double precision NOT NULL,
  adjustment double precision NOT NULL DEFAULT 0,
  total double precision NOT NULL,
  cash_amount double precision NOT NULL DEFAULT 0,
  card_amount double precision NOT NULL DEFAULT 0,
  bank_amount double precision NOT NULL DEFAULT 0,
  gift_amount double precision NOT NULL DEFAULT 0,
  gift_code_used TEXT,
  fiscal_status TEXT NOT NULL DEFAULT 'pending',
  fiscal_document_type TEXT NOT NULL DEFAULT 'receipt',
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sale_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  description TEXT NOT NULL,
  quantity double precision NOT NULL,
  unit_price double precision NOT NULL,
  line_total double precision NOT NULL,
  discount_percent double precision NOT NULL DEFAULT 0,
  item_type TEXT NOT NULL,
  metadata TEXT
);

CREATE TABLE IF NOT EXISTS fiscal_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store TEXT NOT NULL UNIQUE REFERENCES stores(name),
  vendor TEXT NOT NULL,
  model TEXT NOT NULL,
  connector TEXT NOT NULL,
  token_hash TEXT,
  enabled INTEGER NOT NULL DEFAULT 0,
  last_seen_at TEXT,
  last_status TEXT NOT NULL DEFAULT 'not_configured',
  last_error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS fiscal_jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id INTEGER NOT NULL UNIQUE REFERENCES sales(id) ON DELETE CASCADE,
  store TEXT NOT NULL REFERENCES stores(name),
  job_type TEXT NOT NULL,
  payload TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  attempts INTEGER NOT NULL DEFAULT 0,
  device_response TEXT,
  created_at TEXT NOT NULL,
  claimed_at TEXT,
  completed_at TEXT,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS gift_cards (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  beneficiary TEXT NOT NULL,
  initial_value double precision NOT NULL,
  balance double precision NOT NULL,
  expires_at TEXT NOT NULL,
  store TEXT NOT NULL REFERENCES stores(name),
  issued_sale_id INTEGER REFERENCES sales(id) ON DELETE SET NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reservations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  store TEXT NOT NULL REFERENCES stores(name),
  customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  description TEXT NOT NULL,
  kind TEXT NOT NULL,
  total_price double precision NOT NULL,
  deposit_amount double precision NOT NULL,
  balance_due double precision NOT NULL,
  status TEXT NOT NULL,
  issued_sale_id INTEGER REFERENCES sales(id) ON DELETE SET NULL,
  redeemed_sale_id INTEGER REFERENCES sales(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reservation_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id INTEGER NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  description TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price double precision NOT NULL,
  discount_percent double precision NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS transfers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  from_store TEXT NOT NULL REFERENCES stores(name),
  to_store TEXT NOT NULL REFERENCES stores(name),
  sender TEXT NOT NULL,
  receiver TEXT NOT NULL,
  carrier TEXT NOT NULL,
  transport_reason TEXT NOT NULL,
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transfer_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id INTEGER NOT NULL REFERENCES transfers(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  description TEXT NOT NULL DEFAULT '',
  quantity INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS business_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL,
  customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL,
  recipient TEXT NOT NULL,
  recipient_vat_number TEXT,
  recipient_pec TEXT,
  recipient_sdi_code TEXT,
  recipient_address TEXT,
  recipient_postal_code TEXT,
  recipient_city TEXT,
  recipient_province TEXT,
  origin TEXT NOT NULL,
  payment_method TEXT NOT NULL DEFAULT 'cash',
  sale_id INTEGER REFERENCES sales(id) ON DELETE SET NULL,
  net_total double precision NOT NULL DEFAULT 0,
  tax_total double precision NOT NULL DEFAULT 0,
  total double precision NOT NULL,
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS business_document_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id INTEGER NOT NULL REFERENCES business_documents(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  description TEXT NOT NULL,
  quantity double precision NOT NULL,
  unit_price double precision NOT NULL,
  line_total double precision NOT NULL,
  tax_rate double precision NOT NULL DEFAULT 22,
  tax_amount double precision NOT NULL DEFAULT 0,
  gross_total double precision NOT NULL DEFAULT 0
);

-- Log attività (audit): chi ha fatto cosa e quando.
CREATE TABLE IF NOT EXISTS activity_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  username TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id INTEGER,
  detail TEXT NOT NULL DEFAULT '',
  store TEXT
);

-- Indici
CREATE INDEX IF NOT EXISTS activity_log_created_idx ON activity_log(created_at);
CREATE INDEX IF NOT EXISTS activity_log_entity_idx ON activity_log(entity, entity_id);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS customers_name_idx ON customers(last_name, first_name);
CREATE INDEX IF NOT EXISTS sales_customer_idx ON sales(customer_id, created_at);
CREATE INDEX IF NOT EXISTS sales_store_date_idx ON sales(store, created_at);
CREATE INDEX IF NOT EXISTS product_eans_product_idx ON product_eans(product_id);
CREATE INDEX IF NOT EXISTS products_variant_group_idx ON products(variant_group);
CREATE INDEX IF NOT EXISTS inventory_product_idx ON inventory(product_id);
CREATE INDEX IF NOT EXISTS sale_items_sale_idx ON sale_items(sale_id);
CREATE INDEX IF NOT EXISTS sale_items_product_idx ON sale_items(product_id);
CREATE INDEX IF NOT EXISTS reservation_items_reservation_idx ON reservation_items(reservation_id);
CREATE INDEX IF NOT EXISTS transfer_items_transfer_idx ON transfer_items(transfer_id);
CREATE INDEX IF NOT EXISTS fiscal_jobs_store_status_idx ON fiscal_jobs(store, status, created_at);

COMMIT;
